# Generated by Django 4.2.1 on 2023-05-20 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('hrh', 'horror'), ('cmd', 'comedy'), ('ac', 'action')], max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='hollymovies_app.country')),
            ],
        ),
    ]
