# Generated by Django 4.2.1 on 2023-05-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('hrh', 'horror'), ('cmd', 'comedy'), ('ac', 'action')], default='cmd', max_length=20),
        ),
    ]
