# Generated by Django 4.2.1 on 2023-05-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0002_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('hrh', 'horror'), ('cmd', 'comedy'), ('ac', 'action'), ('dr', 'drama')], default='cmd', max_length=20),
        ),
    ]
