# Generated by Django 4.2.1 on 2023-05-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0003_alter_country_options_alter_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actors', to='hollymovies_app.country')),
            ],
        ),
    ]
