# Generated by Django 4.2.1 on 2023-05-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0004_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default='male', max_length=10),
        ),
    ]
