# Generated by Django 4.2.1 on 2023-06-03 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cinemas', to='hollymovies_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_time', models.DateTimeField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_screenings', to='hollymovies_app.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_screenings', to='hollymovies_app.movie')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='screenings',
            field=models.ManyToManyField(related_name='cinemas', through='hollymovies_app.CinemaScreening', to='hollymovies_app.movie'),
        ),
    ]
